name: Run integration test using docker-compose
on: 
  push:
    branches:
      - main 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - name: Build the localdev environment
        run:  make generate_certs
      - name: make
        run: make sut
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results/junit/*.xml
      - name: TearDown
        run: make down
