name: Run integration test using docker-compose
on: 
  push:
    branches:
      - main 
      #- features/lecture5-2
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - name: Build the localdev environment
        run:  make generate_certs
      - name: make
        run: make sut
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./test-results/junit/*.xml
      - name: TearDown
        run: make down
